;;; lsp.el --- LSP settings -*- lexical-binding: t; -*-
;;; Commentary:
;;; LSP settings for my Emacs config.
;;; Code:

;; doom-keybinds.el defines the `map!' macro used in :config below.
;; Load the dependency chain at compile time so the macro is available
;; during byte/native compilation (without this, dotted-pair prefix
;; specs like ("c" . "code") cause a native-compiler error).
(eval-when-compile
  (require 'doom-constants)
  (require 'doom-lib)
  ;; doom-keybinds.el uses (use-package! which-key ...) at the top level,
  ;; which requires doom-use-package to be loaded first (defines use-package!).
  (require 'doom-use-package)
  (require 'doom-keybinds)
  ;; Give the byte-compiler lsp's real definitions rather than piecemeal
  ;; `defvar' / `declare-function' assertions.  With these loaded, the
  ;; `lsp-*' and `lsp-ui-*' assignments in :config are checked against the
  ;; genuine defcustoms -- a typo'd name surfaces as a fresh warning instead
  ;; of being indistinguishable from the rest -- and function references
  ;; such as `lsp-resolve-final-command' are known and arity-checked.  Both
  ;; packages sit in the compile environment via packageRequires in
  ;; emacs-package.nix.
  (require 'lsp-mode)
  (require 'lsp-ui)
  ;; `config/lsp-booster-executable' comes from emacs-config-base-dir.el,
  ;; generated by the Nix build (see emacs-package.nix).  Loading it here
  ;; registers the defvar so the reference below compiles clean.  :no-error
  ;; because outside the Nix build the file legitimately does not exist --
  ;; the same condition the runtime `boundp' guard handles.
  (require 'emacs-config-base-dir nil :no-error))

(require 'use-package)

;; `lsp-execute-code-action' arrives with lsp-mode itself, which the
;; use-package form below requires at load time.  The eval-when-compile
;; require above makes it visible only to the compiler, which therefore
;; warns the keybinding reference "might not be defined at runtime".
;; `declare-function' is the compiler's verifiable assertion -- see
;; `check-declare-file' -- that the runtime provides it.
(declare-function lsp-execute-code-action "lsp-mode" (action))

;; These are pretty big functions to go into an Emacs config, but the
;; providers (emacs-lsp-booster, lsp-mode) provide no means for a library to
;; easily step in.  The recommendation is to use this code, almost verbatim
;; (except for some comments).
;;
;; `emacs-lsp-booster' wraps LSP servers so a helper process converts the
;; server's JSON output into elisp bytecode, which Emacs reads far faster than
;; it parses JSON.
;;
;; The definitions sit at toplevel rather than inside :config below --
;; use-package wraps :config in enough machinery that the byte-compiler loses
;; track of nested defuns and warns their call sites are "not known to be
;; defined".  The :config block only wires them in.
(defun config--lsp-booster-executable ()
  "Return the emacs-lsp-booster binary, or nil if unavailable.
Prefers the nix-store path injected by the build, falling back to PATH
for non-Nix contexts."
  (or (and (boundp 'config/lsp-booster-executable)
           (file-executable-p config/lsp-booster-executable)
           config/lsp-booster-executable)
      (executable-find "emacs-lsp-booster")))

(defun config--lsp-booster-json-parse (old-fn &rest args)
  "Read emacs-lsp-booster's bytecode output when present, else parse JSON."
  (or
   (when (equal (following-char) ?#)
     (let ((bytecode (read (current-buffer))))
       (when (byte-code-function-p bytecode)
         (funcall bytecode))))
   (apply old-fn args)))

(defun config--lsp-booster-final-command (old-fn cmd &optional test?)
  "Prepend emacs-lsp-booster to the resolved LSP server command."
  (let ((orig-result (funcall old-fn cmd test?))
        (booster (config--lsp-booster-executable)))
    (if (and (not test?)
             ;; Boost local servers only; tramp buffers keep plain stdio.
             (not (file-remote-p default-directory))
             ;; The booster's bytecode fast path requires the plists build;
             ;; without it, silently fall through to the plain command.
             lsp-use-plists
             ;; Unnecessary under the native json-rpc of newer Emacsen.
             (not (functionp 'json-rpc-connection))
             booster)
        (progn
          ;; Resolve the command head to an absolute path so the booster
          ;; spawns it directly rather than consulting PATH itself.
          (when-let* ((resolved (executable-find (car orig-result))))
            (setcar orig-result resolved))
          (message "Using emacs-lsp-booster for %s" orig-result)
          (cons booster orig-result))
      orig-result)))

;; LSP_USE_PLISTS is deliberately NOT set here.  `lsp-protocol' reads it once,
;; when it first loads, and this file cannot guarantee it runs first: loaded
;; as source, the `eval-when-compile' requires above run at load time and pull
;; lsp-protocol in before any :init could act.  The Nix-generated
;; `emacs-config-base-dir.el', loaded at the top of `init.el', sets it instead
;; -- the same build that compiled lsp-mode with the flag emits the runtime
;; side.
(use-package lsp-mode
  :config
  ;; Fail loudly on the one misconfiguration this setup can produce.  The
  ;; compiled lsp-interface constructors carry the representation lsp-mode
  ;; was built with; `lsp-use-plists' is what the runtime picked when
  ;; `lsp-protocol' loaded.  When they disagree, every server response fails
  ;; with `wrong-type-argument' and LSP is silently useless, so say so at
  ;; startup instead.
  (when (fboundp 'lsp-make-position)
    (let ((compiled-plists (listp (lsp-make-position :line 0 :character 0)))
          (runtime-plists (and lsp-use-plists t)))
      (unless (eq compiled-plists runtime-plists)
        (display-warning
         'lsp
         (format "lsp-mode was compiled %s plists but the runtime is %s them; \
LSP will not work.  LSP_USE_PLISTS must be set before lsp-protocol first \
loads (see emacs-config-base-dir.el, generated by emacs-package.nix)."
                 (if compiled-plists "with" "without")
                 (if runtime-plists "using" "not using"))
         :error))))
  (advice-add (if (fboundp 'json-parse-buffer) 'json-parse-buffer 'json-read)
              :around #'config--lsp-booster-json-parse)
  (advice-add 'lsp-resolve-final-command :around
              #'config--lsp-booster-final-command)
  ;; Show us more complete and helpful information under the cursor.
  (setq lsp-ui-doc-enable nil)
  (setq lsp-ui-doc-show-with-cursor nil)
  (setq lsp-eldoc-render-all t)          ;; show all info, not truncated
  (setq lsp-idle-delay 0.2)              ;; faster response
  (setq lsp-eldoc-enable-hover t)        ;; enable hover in minibuffer
  (map!
   :mode lsp-mode
   :localleader
   (:prefix
    ("c" . "code")
    :desc "lsp-action" "a" #'lsp-execute-code-action
    )
   )
  )
(provide 'lsp)
;;; lsp.el ends here
