#+title:    Email Emacs Configuration
#+author:   Logan Barnett
#+email:    logustus@gmail.com
#+date:     <2018-01-31 Wed 06:48>
#+language: en
#+tags:     email config

* introduction

  There's a lot of benefits to using Emacs to read and write emails.

  1. I can use text and tagging to search for emails easily.
  2. I can keep keybindings that I am familiar with for both reading and writing
     emails.
  3. Copying text out of emails is easy.
  4. Writing emails can be done with =org-mode=, which means I can use code for
     composing some parts of emails.
  5. I can handle GPG encryption automatically.
  6. My emails can be stored in some universal open source format.
  7. Color scheme is dark.

  Reading and writing email is kind of the holy grail of Emacs configurations.
  Emacs can author emails in =org-mode= and then export them to some email
  format. Amusingly, I think one of the bigger reasons I want email inside of
  emacs right now is the combined vim bindings plus a dark color scheme. Once I
  have replaced Apple Mail as my primary email client, all I have remaining as a
  major hurdle is Apple Calendar, which I think I can replace with Emacs as well
  (but in time).

* tools used
** isync

   =isync= is a library/tool that syncs with an IMAP account (Gmail speaks
   IMAP). =isync= isn't the name of the executable itself. Instead this is
   =mbsync=, and generally I use it with =mbsync -a=. I've found a few blog
   posts to help get me started.

** mu4e

   =mu4e= is the Emacs interface for =mu=, which does email tagging and
   searching. I haven't set this up yet. It needs =mu= itself installed.

   I do have =mu= installed.

**** archiving
     Archiving in =mu4e='s vernacular is "refile". We can set the folder to go
     to the "all mail" folder and then it will work like it should for =gmail=.
#+begin_src emacs-lisp
(defun config/mu4e-set-archive-folder ()
  (setq-default mu4e-refile-folder "/gmail/[Gmail]/.All Mail")
)
#+end_src

**** mail dir
     By default =mu4e= looks for =~/Maildir= which is not where I have my mail
     synced.

#+begin_src emacs-lisp
(defun config/mu4e-set-maildir ()
  (setq-default mu4e-maildir (expand-file-name "~/mail"))
  (setq-default mu4e-change-filenames-when-moving t)
)
#+end_src

**** materials
http://pragmaticemacs.com/emacs/fixing-duplicate-uid-errors-when-using-mbsync-and-mu4e/
http://pragmaticemacs.com/emacs/migrating-from-offlineimap-to-mbsync-for-mu4e/
https://github.com/syl20bnr/spacemacs/issues/6028 - I ran into this issue and
needed to modify the package directly.
http://pragmaticemacs.com/emacs/master-your-inbox-with-mu4e-and-org-mode/

**** images

     Turning on image support is simple.

#+begin_src emacs-lisp
(defun config/mu4e-enable-images ()
  (setq-default mu4e-view-show-images t)
  (setq-default mu4e-view-prefer-html t)
  ;; I think this needs to be registered first? Ensures.
  (when (fboundp 'imagemagick-register-types)
    (imagemagick-register-types))
  )
#+end_src

**** toggling plain-text
     Toggling to plain text is shadowed by =evil-mode=. For now let's provide an
     interactive function to handle it.

     #+begin_src emacs-lisp :results none
       (defun my/mu4e-view-plaintext ()
         "Provide an interactive toggle of plain text and html of mail messages."
         (interactive)
         (setq-default mu4e-view-show-images nil)
         (setq-default mu4e-view-prefer-html nil)
         (setq-default mu4e~view-html-text 'text)
         (setq-default mu4e~message-body-html 'text)
         (mu4e-view-refresh)
         )
     #+end_src

**** DONE add =get-mail= command to mu4e update command
     CLOSED: [2018-08-01 Wed 10:06]
     http://spacemacs.org/layers/+email/mu4e/README.html#configuration

     I should also look at other interesting settings there too.
**** TODO encryption and GPG key
**** getting mail
  =~/bin/mail-sync= gets email and then runs =mu= to perform indexing. This is
  =mu4e= seems to run indexing on its own, so we can just use =mbsync -a= like
  =mail-sync= uses.

#+begin_src emacs-lisp
(defun config/mu4e-sync ()
  (setq-default mu4e-get-mail-command "mbsync -a")
)
#+end_src

**** sending mail

#+begin_src emacs-lisp
  (defun config/send-email ()
    ;; TODO: Many settings are inherited from ../lisp/config-email.el - move them
    ;; here.
    (setq-default
      user-mail-address "logustus@gmail.com"
      user-full-name "Logan Barnett"
      message-send-mail-function 'smtpmail-send-it
      starttls-use-gnutls t
      smtpmail-starttls-credentials '(("smtp.gmail.com" 587 nil nil))
      smtpmail-auth-credentials
        '(("smtp.gmail.com" 587 "logustus@gmail.com" nil))
      smtpmail-default-smtp-server "smtp.gmail.com"
      smtpmail-smtp-server "smtp.gmail.com"
      smtpmail-smtp-service 587
      )
    ;; This allows using `dired' to add attachments. When in `dired-mode', use
    ;; `gnus-dired-attach'. Instructions are more complicated but I'm not sure what
    ;; they are adding since the below is all I needed. See:
    ;; https://www.djcbsoftware.nl/code/mu/mu4e/Dired.html#Dired
    (add-hook 'dired-mode-hook 'turn-on-gnus-dired-mode)
  )
#+end_src
**** bookmarks
     Bookmarks are the initial =b= shortcuts that quickly let me jump to certain
     views. It doesn't come with one that just shows your inbox. I'm not a fan
     of looking at "today's" email unless I can make sure I handle everything in
     a single day.

     #+begin_src emacs-lisp
       (defun config/mu4e-add-bookmarks ()
         "Add mu4e bookmarks."
         (add-to-list 'mu4e-bookmarks
           (make-mu4e-bookmark
             :name  "inbox"
             :query "maildir:/gmail/Inbox"
             :key ?i))
       )
     #+end_src

     Bookmarks can contain lisp expressions as well as parameters in the queries
     themselves.

     [[https://www.djcbsoftware.nl/code/mu/mu4e/Bookmarks.html][mu4e bookmarks docs]]

**** reading: indexing
     This should make reading emails faster. It may, but I've noticed it also
     makes messages in my inbox get lost sometimes. They aren't even in the
     all-mail section. The mail server still shows the message as present in the
     inbox. Removing these statements seems to have fixed it.

     #+begin_src emacs-lisp :results none
       (defun config/mu4e-indexing ()
         ;; (setq-default
          ;; mu4e-index-cleanup nil
          ;; mu4e-index-lazy-check t
          ;; )
         )
     #+end_src

**** reading: mail list
     This prevents scrolling to the next message if you scroll down too far.

     #+begin_src emacs-lisp :results none
       (defun config/mu4e-viewing ()
         (setq-default
          mu4e-view-scroll-to-next nil
          )
         )
     #+end_src

**** reading: format
     #+begin_src emacs-lisp
       (defun config/mu4e-reading-format ()
         (setq-default
          mu4e-html2text-command "iconv -c -t utf-8 | pandoc -f html -t org"
          ;; mu4e-html2text-command "pandoc -f html -t org"
          )
         )
     #+end_src

**** writing
***** line wrapping
      Wrapping at 80 columns is king, but it's not without some management to
      make happen. By default =mu4e= seems to respect single line breaks when
      exporting to the email. This means email readers (such as gmail) will
      break the email at about 78 columns or so, which makes for very poor
      looking, jagged paragraphs. This is partly due to GMail's interaction with
      =format=flowed= for plain text emails, and the RFC governing it.

      Some additional reading:
      + [[https://www.djcbsoftware.nl/code/mu/mu4e/Writing-messages.html][mu4e docs on writing messages]]
      + [[https://mathiasbynens.be/notes/gmail-plain-text][GMail plain text and line wrapping]]
      + [[https://github.com/djcb/mu/issues/569][mu#569]] Support format=flowed on outgoing mails

****** unfill
       I like to edit my emails using =auto-fill-mode= and =fill-paragraph=.
       However we need to "unfill" just before ending. Fortunately a [[https://emacs.stackexchange.com/a/45380/14851][Stack
       Overflow answer]] already does this for us. Below is the code for that,
       mostly verbatim. I changed the call from =fill-paragraph= to
       =mu4e-fill-paragraph= since =fill-paragraph= does the opposite of what we
       want, and =mu4e-fill-paragraph= effectively does the "unfill".

     #+begin_src emacs-lisp :results none
       (defun config/mu4e-unfill-body ()
         (let ((fill-column most-positive-fixnum)
               (top ))
           (mu4e-compose-goto-top)
           (setq top (point))
           (mu4e-compose-goto-bottom)
           ;; now go backward by paragraph and unfill them unless the paragraph starts
           ;; with >
           (while (and (> (point) top)
                       (backward-paragraph))
             (unless (looking-at ">")
               (mu4e-fill-paragraph))))
         )
     #+end_src

****** fill when writing
       For more line wrapping goodness, we need to set up =auto-fill-mode= in
       this buffer again, and also set =fill-column= to 72. 78 should be the
       target, but I'm trying to be conservative here. Once the email is sent,
       it should be "unfilled" (see [[unfill]]) so clients can respect line wraps
       properly.

       We also want to fill some arbitrary text if it was pasted in from a
       source that's not set to our =fill-column= beforehand. By default, =mu4e=
       remaps =M-q= (the standard =fill-paragraph= binding) to
       =mu4e-fill-paragraph=. We want to bring that back as well.

       #+begin_src emacs-lisp :results none

         (defun config/mu4e-prevent-hard-line-wrap-on-export ()
           "Sets `use-hard-newlines' to t for the mu4e buffer."
           (message "opting to use hardlines")
           (setq-default mu4e-compose-format-flowed t)
           (add-hook
            'message-send-hook
            'config/mu4e-unfill-body
            )
           (add-hook
            'mu4e-compose-mode-hook
            (lambda ()
              (setq-local fill-column 72)
              (auto-fill-mode 1)
              (local-set-key (kbd "M-q") 'fill-paragraph)
              )
            )
           )
       #+end_src
****** unfill woes

       Sometimes the paragraph doesn't wrap properly. I've included an example
       below. I'm not sure this is a great problem, nor how it should be fixed.
       I haven't seen it in normal text yet, and I think line wrapping still
       works on clients in most cases. The important part is it doesn't hard
       wrap *abruptly*.

       #+begin_quote
       Pellentesque dapibus suscipit ligula. Donec posuere augue in quam.
       Etiam vel tortor sodales tellus ultricies commodo. Suspendisse potenti.
       Aenean in sem ac leo mollis blandit. Donec neque quam, dignissim in,
       mollis nec, sagittis eu, wisi. Phasellus lacus. Etiam laoreet quam sed
       arcu. Phasellus at dui in ligula mollis ultricies. Integer
       placerat tristique nisl. Praesent augue. Fusce commodo. Vestibulum convallis, lorem a tempus semper, dui dui euismod elit, vitae placerat urna tortor
       vitae lacus. Nullam libero mauris, consequat quis, varius et, dictum id,
       arcu. Mauris mollis tincidunt felis. Aliquam feugiat tellus ut
       neque. Nulla facilisis, risus a rhoncus fermentum, tellus tellus lacinia purus,
       et dictum nunc justo sit amet elit.
       #+end_quote
***** composition

      We shouldn't reply to ourselves when doing a reply.
      #+begin_src emacs-lisp :results none
        (defun config/mu4e-composing ()
          (setq-default
           mu4e-compose-dont-reply-to-self t
           )
          )
      #+end_src
**** evilication

     #+begin_src emacs-lisp :results none
       (defun config/mu4e-evilify-evil-window-prefix ()
         "Setup window prefixed commands"
         (interactive)
         ;; The docs state you can use the mode name directly instead of a map within
         ;; it. This resolves problems where certain modes seem to ignore
         ;; `evil-define-key'.
         ;; https://github.com/noctuid/evil-guide#why-dont-keys-defined-with-evil-define-key-work-immediately
         (mapc
          (lambda (keymap)
            (evil-define-key 'evilified keymap
              (kbd "C-w h") 'evil-window-left
              (kbd "C-w j") 'evil-window-down
              (kbd "C-w k") 'evil-window-up
              (kbd "C-w l") 'evil-window-right
              (kbd "C-w v") 'evil-window-vsplit
              (kbd "C-w s") 'evil-window-split
              (kbd "C-w =") 'balance-windows
              ;; TODO: More to come with other window functions.
              ;; TODO: Consider using https://github.com/emacs-evil/evil-collection
              ;; TODO: Consider generalizing this for other modes
              )
            )
          '(mu4e-view-mode-map mu4e-headers-mode-map)
          )
         (evil-normalize-keymaps)
         (message "window prefix configured")
         )
     #+end_src

**** apply mu4e

#+begin_src emacs-lisp :results none

  (defun gmail-archive ()
    "Archive the current or marked mails.
  This moves them into the All Mail folder."
    (interactive)
    (gnus-summary-move-article nil "nnimap+imap.gmail.com:[Gmail]/All Mail"))

  (defun gmail-report-spam ()
    "Report the current or marked mails as spam.
  This moves them into the Spam folder."
    (interactive)
    (gnus-summary-move-article nil "nnimap+imap.gmail.com:[Gmail]/Spam"))

  (require 'use-package)
  (message "initializing mu4e with use-package...")
  (use-package "mu4e"
    :defer t
    :config
    (message "initializing mu4e...")
    (require 'org-mime)
    (config/mu4e-add-bookmarks)
    ;; (config/mu4e-enable-images)
    (config/mu4e-set-maildir)
    (config/mu4e-set-archive-folder)
    (config/mu4e-sync)
    (config/send-email)
    (config/mu4e-evilify-evil-window-prefix)
    (config/mu4e-indexing)
    (config/mu4e-viewing)

    (load-library "my-utils")
    ;; No idea why setq-local is needed here, and elsewhere defvar-local works.
    ;; This would be a great question for the emacs user group.

    ;; Copy key-id.template.txt to ~/.emacs.d/private/key-id.txt and populate with
    ;; the key ID.
    ;; What key ID?
    (setq-local key-id
                (my-utils/get-string-from-file  "~/.emacs.d/private/key-id.txt")
                )
    (message "loaded key id %s" key-id)
    (setq-default
    user-mail-address "logustus@gmail.com"
    mml-2015-signers key-id
    gnus-select-method
    '(nnimap "gmail"
              (nnimap-address "imap.gmail.com")
              (nnimap-server-port 993)
              (nnimap-stream ssl)
              )
    ;; u 41E46FB1ACEA3EF0 Logan Barnett (gpg key) <logustus@gmail.com>
    smtpmail-smtp-server "smtp.gmail.com"
    smtpmail-smtp-service 587
    message-send-mail-function 'smtpmail-send-it
    ;; nntp-authinfo-file "~/.nntp-authinfo.gpg"
    nntp-authinfo-file "~/.authinfo.gpg"
    ;; Gmail system labels have the prefix [Gmail], which matches the default
    ;; value of gnus-ignored-newsgroups. That's why we redefine it.
    gnus-ignored-newsgroups "^to\\.\\|^[0-9. ]+\\( \\|$\\)\\|^[\"]\"[#'()]"
    ;; The agent seems to confuse nnimap, therefore we'll disable it.
    gnus-agent nil
    ;; We don't want local, unencrypted copies of emails we write.
    gnus-message-archive-group nil
    ;; We want to be able to read the emails we wrote.
    mml2015-encrypt-to-self t
    ;; mu4e-view-prefer-html nil
    ;; mu4e-html2text-command "html2text -utf8 -width 72"
    ;; mu4e-html2text-command "html2markdown | grep -v '&nbsp_place_holder;'"

    ;; This is a MacOS specific solution. It just flattens the text so it's not
    ;; very preferable, but unlike the shr stuff, it doesn't create a bunch of
    ;; hanging file handles that require a reboot sometime later.
    ;; mu4e-html2text-command "textutil -stdin -format html -convert txt -stdout"
    ;; mu4e-view-html-plaintext-ratio-heuristic most-positive-fixnum
    )
    ;; Attempt to encrypt all the mails we'll be sending.
    (add-hook 'message-setup-hook 'mml-secure-message-encrypt)

    (config/mu4e-reading-format)
    (config/mu4e-prevent-hard-line-wrap-on-export)
    (message "done initializing mu4e")
    )
#+end_src

** notmuch                                                          :ARCHIVE:

   =notmuch= is installed as a =spacemacs= layer. There's a
   [[https://github.com/cmiles74/spacemacs-notmuch-layer][spacemacs-notmuch-layer]] repository for this, as it is not built in. Not much
   is just a way of navigating and tagging emails. It doesn't handle the
   syncing.

   Aside from the layer linked above, there's also a =notmuch= layer sitting in
   the =develop= branch of Spacemacs [[https://github.com/syl20bnr/spacemacs/issues/2163][spacemacs #2163]]. It has not made its way to
   a release branch yet.

*** keybindings

    The keybindings here are in sore need of love for something that works for
    my muscle memory.

    |   |   |   |
    |---+---+---|
    | s |   | search emails |
    |   |   |   |
    |   |   |   |
    |   |   |   |

* research

  - [[https://www.reddit.com/r/emacs/comments/4rl0a9/email_in_emacs_i_want_to_but_wow_its_overwhelming/d52q08p/][IceDane's Emacs email setup]] :: =IceDane= has very good rationale of the
       setup they use and goes through all of the things they have tried. I want
       to closely follow this setup.
  - [[https://notmuchmail.org/notmuch-emacs/][notmuch Emacs interface]] :: Official documentation for using =notmuch= with
       Emacs.
  - [[https://wiki.archlinux.org/index.php/Isync][ArchLinux isync config]] :: Tutorial on setting up =isync=.
  - [[http://www.ict4g.net/adolfo/notes/2014/12/27/emacs-imap.html][Adolfo Villafiorita's IMAP in Emacs + MacOS setup]] :: This has been a rich
       trove of information about a setup similar to =IceDane='s. It includes a
       little bit alternatives and also different approaches with additional
       passes on existing configs (such as adding oauth support via Gmail).
  - [[https://www.reddit.com/r/emacs/comments/7me0vn/help_configuring_mbsyncrc_for_gmail_on_osx/][isync "unknown section keyword" problem]] :: I ran into this problem. The fix
       is that sections are grouped together by a lack of an extra line break.
       Extra linebreak (two in a row) means there's a new section.
  - [[https://docwhat.org/el-capitan-and-the-evils-of-openssl/][OpenSSL and CertificateFile]] :: Homebrew provides a pem file that can be used
       in the =CertificateFile= field for =.mbsyncrc= (=isync='s config file).
       This gives us the root certificate authority needed to establish a chain
       of trust with gmail's certificates.

* alternative tools

*** gnus

    I have tried =gnus= which is built into Spacemacs as a layer. =gnus= is
    meant as more of an RSS aggregator than anything else. I had a lot of
    trouble syncing with Gmail, writing emails, and reading them. The
    documentation for evilication is sparse at best, and I just get the feel
    that while using =gnus= for email is clever, it just feels like stretching a
    tool to be something it isn't.
* reference

  - [[https://www.emacswiki.org/emacs/NotMuch][Emacs Wiki - NotMuch]] :: Has some scripts that might be helpful later, and
       links to other sources and integrations with other tools.
  - [[https://github.com/tjim/nevermore][nevermore]] :: A =notmuch= interface for Emacs. I'm not sure what it provides
       over the =notmuch= official Emacs plugin yet. =company= support?
  - [[https://github.com/cmiles74/spacemacs-notmuch-layer][Spacemacs notmuch layer]] :: =notmuch= for Spacemacs. Use =SPC a n= to activate.
  - [[https://notmuchmail.org/notmuch-emacs/][notmuch-emacs]] :: Official docs on setting up =notmuch= with Emacs.
* artifacts
