#+title:     LaTeX
#+author:    Logan Barnett-Hoy
#+email:     logustus@gmail.com
#+date:      <2020-06-06 Sat>
#+language:  en
#+file_tags:
#+tags:

* configuration
See [[file:./org-mode.org::*latex][org-mode.org::*latex]] for configuration for LaTeX. This file is somewhat for
reference because I often forget the keybindings and how to apply LaTeX, and
this is where I will look first for LaTeX settings. It's in the =org-mode= file
so I can have =use-package= used for =org-mode= once and only once.

* debugging
** caching
=org-latex= will cache any rendered images it creates. When changing settings it
is meaningless to test the same script. Make a minor change to get it to
re-render. Or delete the cache files.

Delete the files located at whatever =org-preview-latex-image-directory= is set
to. Normally it's set to a relative =ltximg/= but for some reason it's under
=~/.emacs.d/.local/cache=. While the files will essentially always be unique,
I'm not sure how I feel about this. I can revisit it later.

* pronounciation
LaTeX is pronounced "Latek", Because Reasons.
* latex examples

LaTeX has an atypical relationship with =org-mode=. It can render inline using
special syntax, notably surrounding with =$= or =\(...\)=. The default
keybinding to render such syntax inline is =C-c C-x C-l=. The pause should be
very brief.

** code blocks
Code blocks like this will not work:
#+begin_latex :results raw :file test.png
  x=\sqrt(b)
#+end_latex

Nor will code blocks like this:
#+begin_src latex :results raw :file test.png
\begin{equation} % arbitrary environments
x=\sqrt(b)       % even tables, figures
\end{equation}   % etc
#+end_src

\begin{equation} % arbitrary environments
x=\sqrt(b)       % even tables, figures
\end{equation}   % etc

** inline

If $a^2=b$ and \( b=2 \), then the solution must be
either $$ a=+\sqrt{2} $$ or \[ a=-\sqrt{2} \].
** division

To do a column-stacked division, or in other words a fraction, use
=\dfrac{numerator}{demoninator}=, where =numerator= and =demoninator= are
expressions for the fraction.

$\dfrac{1}{2}$

$\dfrac{2}{3}$
** circuit diagrams

Using =tikz= and =circuitikz=, circuit diagrams can be rendered and ideally
previewed. This requires some additional setup. Once it's configured, this
should show a simple circuit diagram. Use =C-c C-x C-l= to toggle the preview.

There is an issue where [[https://github.com/circuitikz/circuitikz/issues/429][components are not colored]]. The work around is to add
this after the =begin= statement:

#+begin_latex
\ctikzset{color/.initial=gray}
#+end_latex


\begin{circuitikz}[]
\ctikzset{color/.initial=gray}
\draw (0,0) to[isource] (0,3) -- (2,3)
to[R] (2,0) -- (0,0);
\end{circuitikz}

\begin{circuitikz}[american, scale = 1.5][americanvoltages]
\ctikzset{color/.initial=gray}
  \draw (0,0)
  to[V=$V_{in}$] (0,2) % The voltage source
  to[R, v^<=$R_1$] (2,2) % The resistor
  to[C, v^<=$C_1$] (2,1) % Capacitor One
  to[C, v^<=$C_2$] (2,0) %Capacitor Two
  to[L, v^<=$L_1$] (0,0); %Inductor One

\draw[thin, <-, >=triangle 45] (1,1)node{$i_1$}  ++(-60:0.5) arc (-60:170:0.5);

\end{circuitikz}

#+LATEX_HEADER_EXTRA: \usepackage[siunitx, RPvoltages]{circuitikz}
#+begin_latex
\begin{circuitikz}[american, scale = 1.5][americanvoltages]
  \draw (0,0)
  to[V=$V_{in}$] (0,2) % The voltage source
  to[R, v^<=$R_1$] (2,2) % The resistor
  to[C, v^<=$C_1$] (2,1) % Capacitor One
  to[C, v^<=$C_2$] (2,0) %Capacitor Two
  to[L, v^<=$L_1$] (0,0); %Inductor One

\draw[thin, <-, >=triangle 45] (1.25,0.5) arc (-60:170:0.5);

\end{circuitikz}
#+end_latex
