#+title:     Lisp
#+author:    Logan Barnett
#+email:     logustus@gmail.com
#+date:      <2021-03-11 Thu>
#+language:  en
#+file_tags:
#+tags:

* advice

Sometimes we need to completely unadvise a function, regardless of what advice
it already has.

Note: I have not seen this always work in all circumstances. Further
investigation is needed. ~advice-mapc~ was not iterating over all of the advice.

#+name: config/advice-unadvice
#+begin_src emacs-lisp :results none :tangle yes
(defun advice-unadvice (sym)
  "Remove all advices from symbol SYM."
  (interactive "aFunction symbol: ")
  (message "Removing advice from %s" sym)
  (advice-mapc (lambda (advice _props)
                 (message "Removed %s from %s" advice sym)
                 (advice-remove sym advice))
               sym))
#+end_src

* file local variables

** prompt if unsafe
Things like =.dir-locals.el= and =org= files can have certain variables set from
the file itself. While some of these are safe, some of these are unsafe. Doom
has decided in this [[https://github.com/hlissner/doom-emacs/commit/5e7864838a7f65204b8ad3fe96febc603675e24a][commit]] that the prompting should be disabled by default.
While I agree that we should prompt less, I also think that it's far too easy to
miss a message in the minibuffer, and then we're wondering why =noweb= isn't
working inside of our literate =org= file anymore. Set it back to prompting. =t=
means to accept all "safe" variables and prompt if unsafe variables are present.

#+name: config/lisp-file-local-variables-prompt-if-unsafe
#+begin_src emacs-lisp :results none :tangle no
(setq-default enable-local-variables t)
#+end_src

* safe variables

#+name: config/lisp-safe-local-variable-values
#+begin_src emacs-lisp :results none :tangle no
;; Just repeat this as needed.  These allow a predicate to determine values.
;; Setting `safe-local-variable-values' is static and only allows one value.
(put 'c-block-comment-prefix 'safe-local-variable #'stringp)
(put 'indicate-empty-lines 'safe-local-variable #'booleanp)
;; Eval is a little more tricky, but I want to support these:
;; (eval . (c-set-offset 'innamespace 0))
;; (eval . (c-set-offset 'defun-open 0))
;; (eval . (c-set-offset 'inline-open 0))
;; (eval . (c-set-offset 'arglist-intro '+))
;; (eval . (c-set-offset 'arglist-cont 0))
;; (eval . (c-set-offset 'arglist-cont-nonempty '+))
;; (eval . (c-set-offset 'substatement-open 0))
;; (eval . (c-set-offset 'access-label '-))
;; (eval . (c-set-offset 'inlambda 0))
#+end_src


* string truncation in package.el

I'm going to leave this as reference, since it turned out to be a wild goose
chase.

Lines in =package.el= for Doom look like this:

#+begin_example emacs-lisp :results none
(package! evil-nerd-commenter :pin "b8ac35fe01...")
#+end_example

It may be using the actual ellipsis character, which may or may not render as 3
columns.

=+emacs-lisp-truncate-pin= exists to truncate git SHA hashes as part of
fontification. I did witness an example of it truncating the wrong thing, but
attempts to reproduce this have failed.

This is a relatively harmless change. If I yank the link it belongs to and paste
it elsewhere, it will initially appear to have preserved the ellipsis. However
this is because the fontification survived the yank. It will be written to disk
with the appropriate, full value. When the buffer is reloaded (assuming it is
not a =package.el= or perhaps a Lisp file), it should show the non-fontified
version: meaning it has no ellipsis.

If I need to disable it for whatever reason, change the =example= block below
into a =src= block.

#+begin_example emacs-lisp
(defun config/truncate-string-stop (orig-fn &rest args)
  "Intentionally block truncation."
  )
(advice-add '+emacs-lisp-truncate-pin :around #'config/truncate-string-stop)
(advice-remove '+emacs-lisp-truncate-pin)
#+end_example

Don't actually remove this just yet.
#+begin_src emacs-lisp :results none
;(advice-remove '+emacs-lisp-truncate-pin #'config/truncate-string-stop)
#+end_src
* string manipulation
** fill a string

#+name: config/fill-string
#+begin_src emacs-lisp :results none :tangle yes
(defun fill-string (s)
  "Fill string S (hard line wrap)."
  (with-temp-buffer
    (markdown-mode)
    (insert s)
    (fill-region (point-min) (point-max))
    (buffer-substring (point-min) (point-max))
    )
  )
#+end_src

* indentation

See [[file:./prog-mode.org::*indent align fix]] for a description of alignment in
Emacs in a general sense.

The before and after looks the same with =lisp-backquote-indentation= set to
=nil=. Perhaps this construct is wrong.

#+begin_example emacs-lisp
(setq-default
 big-list
 '(
   foo
   bar
   baz
   ))
#+end_example

#+begin_example emacs-lisp
(setq-default
 big-list
 '(
   foo
   bar
   baz
   ))
#+end_example

#+name: config/lisp-indentation-align-fix
#+begin_src emacs-lisp :results none :tangle no
(setq-default lisp-backquote-indentation nil)
#+end_src

* structural editing

Lispyville provides vim-style structural editing for Lisp code without the
auto-pairing headaches of smartparens.  It gives us slurp/barf operations and
sexp-aware text objects.

** slurp and barf

Slurp pulls the next element into the current form.  Barf pushes the last
element out of the current form.

- ~gs~ slurp forward (pull next element in)
- ~gS~ slurp backward (pull previous element in)
- ~gb~ barf forward (push last element out)
- ~gB~ barf backward (push first element out)

** text objects

- ~f~ form/sexp (works like ~w~ for words, ~p~ for paragraphs)
- ~daf~ delete a form
- ~vif~ select inside form
- ~yaf~ yank a form

#+name: config/lispyville
#+begin_src emacs-lisp :results none :tangle no
(use-package lispyville
  :hook ((emacs-lisp-mode . lispyville-mode)
         (lisp-mode . lispyville-mode)
         (scheme-mode . lispyville-mode)
         (clojure-mode . lispyville-mode))
  :config
  ;; Enable key themes.  We use:
  ;; - operators: adds operator support for structural editing
  ;; - text-objects: adds 'f' for form text objects
  ;; We explicitly do NOT enable atom-movement, slurp/barf-cp (which use
  ;; conflicting keys), or any additional features that might interfere with
  ;; existing evil bindings.
  (lispyville-set-key-theme
   '(operators
     text-objects))

  ;; Custom slurp/barf bindings using gs/gS and gb/gB.  We use paredit's
  ;; explicit directional commands for clear forward/backward control.  Paredit
  ;; is loaded only for these commands; paredit-mode itself is not enabled.
  (evil-define-key 'normal lispyville-mode-map
    (kbd "gs") 'paredit-forward-slurp-sexp   ; slurp forward (pull next in)
    (kbd "gS") 'paredit-backward-slurp-sexp  ; slurp backward (pull previous in)
    (kbd "gb") 'paredit-forward-barf-sexp    ; barf forward (push last out)
    (kbd "gB") 'paredit-backward-barf-sexp)  ; barf backward (push first out)
  )
#+end_src

* stitch

#+begin_src emacs-lisp :results none :noweb yes
<<config/advice-unadvice>>
<<config/fill-string>>
(use-package "lisp-mode"
  :init
  <<config/lisp-safe-local-variable-values>>
  <<config/lisp-file-local-variables-prompt-if-unsafe>>
  <<config/lisp-indentation-align-fix>>
  )
<<config/lispyville>>
#+end_src
