#+title:     Rust
#+author:    Logan Barnett-Hoy
#+email:     logustus@gmail.com
#+date:      <2020-09-10 Thu>
#+language:  en
#+file_tags:
#+tags:

* rust-mode vs rustic-mode

=rust-mode= doesn't seem to be keeping up well with evolving deprecations in the
Rust toolchain (such as deprecating =racer= and =rls=). For this reason I have
chosen =rustic-mode=. I thought I used it before, but didn't record reasons for
switching. This might be sitting in the git history for this file.

* indentation

As a huge proponent to 80 columns, I find Rust's 4 space indent to be an awful
choice. Their code formatting uses it, and the community uses it. So trying to
change it seems like a lost cause. That's okay though, because we have
=redshift=.

Ever since installing =highlight-indent-guides-mode=, =redshift-indent-mode= no
longer works alongside it.

#+name: config/rust-redshift
#+begin_src emacs-lisp :results none :tangle no

;; (defun config/rust-redshift-fix-indentation ()
;;   (setq-local redshift-cosmological-constant 0.5)
;;   (redshift-indent-mode)
;;   (redshift-indent -2)
;;   )
;; (add-hook 'rustic-mode-hook #'config/rust-redshift-fix-indentation)
(message "Skipping redshift-indent-mode for rust until we can figure out how to make it play nice with highlight-indent-guides-mode.")
#+end_src
* racer

=racer= is deprecated, as is =rls=. Prefer =rust-analyzer= now.

* multi-line

I like trailing commas, and Rust supports them everywhere! See the default
strategy in [[file:./prog-mode.org]].

#+name: config/rust-multi-line-commas
#+begin_src emacs-lisp :results none :tangle no
(multi-line-defhook rustic-mode multi-line-add-trailing-comma-strategy t)
#+end_src


* smart-parens

I haven't found the cause yet, but it appears that =rustic= is pulling in and
using =smart-parens=. Disable it. Always.

#+name: config/smartparens-disable
#+begin_src emacs-lisp :results none :tangle no
(defun config/rust-smartparens-disable ()
  (smartparens-global-mode 0)
  )
(add-hook 'rustic-mode-hook #'config/rust-smartparens-disable)
#+end_src

* stitch

#+begin_src emacs-lisp :results none :noweb yes
(use-package "rustic"
  :init
  (message "add rust to path manually...")
  (add-to-list 'exec-path (expand-file-name "~/.nix-profile/bin"))
  (add-to-list 'exec-path (expand-file-name "~/.nix-profile/bin"))
  <<config/smartparens-disable>>
  <<config/rust-redshift>>
  :config
  ;; Needed to take advantage of config/rust-multi-line-commas.
  (require 'multi-line)
  <<config/rust-multi-line-commas>>
  )
#+end_src
