#+title:     SCAD
#+author:    Logan Barnett-Hoy
#+email:     logustus@gmail.com
#+date:      <2021-05-09 Sun>
#+language:  en
#+file_tags:
#+tags:

* preview

** executable

My executable isn't found in =$PATH= due to how Homebrew exposes OpenSCAD. While
the Nix OpenSCAD package doesn't suffer this, the Nix package doesn't function
currently on =aarch64=.

The path must be expanded before being set.

#+name: config/openscad-command
#+begin_src emacs-lisp :results none :tangle yes
(setq-default scad-command (file-truename "~/bin/openscad"))
#+end_src


** key maps

The movement key bindings here are relative to the camera, not the model. When
the camera moves to the left (-x), the model(s) will appear to move right.

#+name:config/scad-preview-keymap
#+begin_src emacs-lisp :results none :tangle no
(map!
 :map scad-preview--image-mode-map
 :n "h" 'scad-preview-trnsx-
 :n "j" 'scad-preview-trnsz-
 :n "k" 'scad-preview-trnsz+
 :n "l" 'scad-preview-trnsx+
 )
#+end_src

* scad-mode

** key bindings

We need a binding to bring up the preview easily.

#+name: config/scad-keymap
#+begin_src emacs-lisp :results none :tangle no
;; Normalizing the keymaps seems to make the below actually stick. See
;; https://github.com/hlissner/doom-emacs/commit/1f5dae917677fc32ef75645c2d5225293c79d893
;; for inspiration.
(add-hook 'scad-mode-hook #'evil-normalize-keymaps)
(map!
 :map scad-mode-map
 :localleader
  :desc "Preview SCAD file" "p" #'scad-preview-mode
  )
#+end_src

** indentation
*** disable hanging indentation

See [[file:./prog-mode.org::*indent align fix]] for a description of alignment in
Emacs in a general sense.

Aligned indentation has made its way into =scad-mode=. From poking around
=scad-mode=, it looks like it uses C settings. See [[./prog-mode.org::*indentation]]
for reference.

#+name: config/scad-indentation-fix
#+begin_src emacs-lisp :results none :tangle no
(setq-default scad-indent-style "1tbs-no-align")
#+end_src

* org-babel

We can add =org-babel= support using [[https://github.com/wose/ob-scad][ob-scad]].

#+name: config/org-babel-ob-scad-add
#+begin_src emacs-lisp :results none
(org-babel-do-load-languages
 'org-babel-load-languages
 '(scad . t)
 )
#+end_src


* stitch

#+begin_src emacs-lisp :results none :noweb yes
(use-package "scad-mode"
  :init
  <<config/scad-preview-keymap>>
  <<config/scad-keymap>>
  <<config/prog-mode-fix-c-indentation>>
  <<config/scad-indentation-fix>>
  <<config/org-babel-ob-scad-add>>
  <<config/openscad-command>>
  (add-hook 'scad-mode-hook #'config/prog-mode-c-style-set)
  )
#+end_src
