#+title:    yasnippet
#+author:   Logan Barnett
#+email:    logustus@gmail.com
#+date:     <2018-09-11 Tue>
#+language: en
#+tags:     yasnippet emacs config

* fundamental-mode
  Per this [[https://github.com/joaotavora/yasnippet/issues/557][ticket]], =fundamental-mode= doesn't have a =fundamental-mode-hook=. We
  can get around this issue for emacs-wide snippets by adding a hook onto the
  =yasnippet= minor mode.

  #+begin_src emacs-lisp
    (defun config/yasnippet-fundamental-mode ()
      "Make sure we use snippets in `fundamental-mode' globally."
      (add-hook 'yas-minor-mode-hook
                (lambda ()
                  (yas-activate-extra-mode 'fundamental-mode)))
      )
  #+end_src
* file templates
File templates are templates that expand for new or blank files. This is a
feature introduced in Doom via the =file-templates= editor module.

Setting the =+file-templates-dir= gives us the power to override the templates.
However this isn't a great way to support a mix of both private and official
packages. An undocumented way to support overrides is to place a =__= file in
the appropriate snippet directory. For specifically named files, =__<filename>=
works as well. The key for these files is assumed to be =__= and we should
continue that when writing file templates.

* apply

  #+begin_src emacs-lisp :results none
    (require 'use-package)

    (use-package "yasnippet"
      :init
      (setq-default yas-snippet-dirs '("~/dev/dotfiles/yasnippets"))
      (config/yasnippet-fundamental-mode)
      :config
      (yas-recompile-all)
      (yas/reload-all)
      )
  #+end_src
